import { Router } from 'express';
import authRoutes from '../features/auth/auth.routes.ts';
import staffRoutes from '../features/staff/staff.routes.ts';
import customerRoutes from '../features/customers/customer.routes.ts';
import maintenanceRoutes from '../features/maintenance/maintenance.routes.ts';
import discountsRoutes from '../features/discounts/discounts.routes.ts';
import bookingRoutes from '../features/booking/booking.routes.ts';
import groomingRoutes from '../features/grooming/grooming.routes.ts';
import daycareRoutes from '../features/daycare/daycare.routes.ts';
import veterinaryRoutes from '../features/veterinary/veterinary.routes.ts';
import hotelRoutes from '../features/hotel/hotel.routes.ts';
import branchesRoutes from '../features/branches/branches.routes.ts';
import catalogRoutes from '../features/catalog/catalog.routes.ts';
import billingRoutes from '../features/billing/billing.routes.ts';
import paymongoWebhookRoutes from '../features/billing/routes/paymongoWebhook.routes.ts';
import creditsRoutes from '../features/credits/credits.routes.ts';
import notificationsRoutes from '../features/notifications/notifications.routes.ts';
import messagingRoutes from '../features/messaging/messaging.routes.ts';
import reportsRoutes from '../features/reports/reports.routes.ts';
import publicRoutes from '../features/public/public.routes.ts';

const router = Router();

router.use(authRoutes);
router.use(staffRoutes);
router.use(customerRoutes);
router.use(maintenanceRoutes);
router.use(discountsRoutes);
router.use(bookingRoutes);
router.use(groomingRoutes);
router.use(daycareRoutes);
router.use(veterinaryRoutes);
router.use(hotelRoutes);
router.use(branchesRoutes);
router.use(catalogRoutes);
router.use(billingRoutes);
router.use(paymongoWebhookRoutes);
router.use(creditsRoutes);
router.use(notificationsRoutes);
router.use(messagingRoutes);
router.use(reportsRoutes);
router.use(publicRoutes);

export default router;
